kind = "web"
previewPath = "/"
title = "PK Site"
version = "1.0.0"
id = "artifacts/pk-site"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25606

[services.development]
run = "pnpm --filter @workspace/pk-site run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pk-site", "run", "build" ]
publicDir = "artifacts/pk-site/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25606"
BASE_PATH = "/"
