// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pk-landings/Constellation.tsx": () => import("../components/mockups/pk-landings/Constellation.tsx"),
  "./components/mockups/pk-landings/LatestPost.tsx": () => import("../components/mockups/pk-landings/LatestPost.tsx"),
  "./components/mockups/pk-landings/Manifesto.tsx": () => import("../components/mockups/pk-landings/Manifesto.tsx"),
  "./components/mockups/pk-landings/Signature.tsx": () => import("../components/mockups/pk-landings/Signature.tsx"),
  "./components/mockups/pk-landings/TimeAndPlace.tsx": () => import("../components/mockups/pk-landings/TimeAndPlace.tsx")
};
