// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pk-day-landings/Atmospheric.tsx": () => import("../components/mockups/pk-day-landings/Atmospheric.tsx"),
  "./components/mockups/pk-day-landings/Composed.tsx": () => import("../components/mockups/pk-day-landings/Composed.tsx"),
  "./components/mockups/pk-landings/Atmospheric.tsx": () => import("../components/mockups/pk-landings/Atmospheric.tsx"),
  "./components/mockups/pk-landings/Composed.tsx": () => import("../components/mockups/pk-landings/Composed.tsx"),
  "./components/mockups/pk-landings/Current.tsx": () => import("../components/mockups/pk-landings/Current.tsx"),
  "./components/mockups/pk-landings/Gold.tsx": () => import("../components/mockups/pk-landings/Gold.tsx")
};
